"""initial tables

Revision ID: a6a4deff5a2a
Revises: 
Create Date: 2026-03-31 12:58:31.925766
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a6a4deff5a2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_characters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('animal_type', sa.String(length=50), nullable=False),
    sa.Column('personality_summary', sa.String(length=500), nullable=False),
    sa.Column('voice_style', sa.String(length=100), nullable=False),
    sa.Column('default_color_palette_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('themes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=False),
    sa.Column('age_max', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('auth_provider', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('child_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('age_band', sa.String(length=10), nullable=False),
    sa.Column('favorite_teacher_id', sa.Uuid(), nullable=True),
    sa.Column('preferred_theme', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['favorite_teacher_id'], ['teacher_characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('teacher_character_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('asset_name', sa.String(length=100), nullable=False),
    sa.Column('asset_url', sa.String(length=500), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_character_id'], ['teacher_characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_profile_id', sa.Uuid(), nullable=False),
    sa.Column('teacher_character_id', sa.Uuid(), nullable=False),
    sa.Column('theme_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_profile_id'], ['child_profiles.id'], ),
    sa.ForeignKeyConstraint(['teacher_character_id'], ['teacher_characters.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('speaker', sa.String(length=20), nullable=False),
    sa.Column('message_text', sa.String(length=2000), nullable=False),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drawing_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('background_color', sa.String(length=20), nullable=False),
    sa.Column('snapshot_image_url', sa.String(length=500), nullable=True),
    sa.Column('recognized_scene_summary', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('story_text', sa.Text(), nullable=False),
    sa.Column('narration_text', sa.Text(), nullable=True),
    sa.Column('age_band', sa.String(length=10), nullable=True),
    sa.Column('generated_by_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_assists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drawing_page_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_source', sa.String(length=50), nullable=False),
    sa.Column('child_context_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('inferred_intent', sa.String(length=200), nullable=True),
    sa.Column('assist_style', sa.String(length=50), nullable=True),
    sa.Column('overlay_strokes_json', sa.JSON(), nullable=True),
    sa.Column('explanation_text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drawing_page_id'], ['drawing_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comic_books',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('format_type', sa.String(length=50), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strokes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drawing_page_id', sa.Uuid(), nullable=False),
    sa.Column('stroke_type', sa.String(length=20), nullable=False),
    sa.Column('points_json', sa.JSON(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('tool', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['drawing_page_id'], ['drawing_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comic_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('comic_book_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('panel_number', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption_text', sa.String(length=500), nullable=True),
    sa.Column('narration_text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comic_book_id'], ['comic_books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comic_pages')
    op.drop_table('strokes')
    op.drop_table('comic_books')
    op.drop_table('ai_assists')
    op.drop_table('stories')
    op.drop_table('drawing_pages')
    op.drop_table('conversations')
    op.drop_table('projects')
    op.drop_table('teacher_assets')
    op.drop_table('child_profiles')
    op.drop_table('users')
    op.drop_table('themes')
    op.drop_table('teacher_characters')
    # ### end Alembic commands ###
